version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - depguard
    - gochecksumtype
    - goconst
    - govet
    - errcheck
    - ineffassign
    - intrange
    - modernize
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
  disable:
    - unparam
  settings:
    depguard:
      rules:
        Main:
          deny:
            - pkg: github.com/go-kit/kit/log
              desc: Use github.com/go-kit/log instead of github.com/go-kit/kit/log
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: (.+)_test\.go
      - path: (.+)\.go$
        text: Error return value of .*log\.Logger\)\.Log\x60 is not checked
      - path: (.+)\.go$
        text: defers in this range loop won't run unless the channel gets closed
      - path: (.+)\.go$
        text: func name will be used as proxy.ProxyHandler by other packages, and that stutters; consider calling this Handler
      - path: (.+)\.go$
        text: ineffectual assignment to dialTimeout
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
