version: 2
project_name: lokxy

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

report_sizes: true

archives:
  - format: tar.gz
    files:
      - LICENSE

builds:
  - main: ./cmd/
    binary: lokxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Tag }} -X main.Revision={{ .ShortCommit }}
