FROM golang:1.25 AS builder

ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETOS
ENV GOARCH=${TARGETARCH} GOOS=${TARGETOS}

WORKDIR /go/src/github.com/paulojmdias/lokxy
COPY go.mod go.sum ./
RUN go mod download 

COPY . ./
RUN make build

FROM gcr.io/distroless/static-debian13:nonroot

EXPOSE 3100

COPY --from=builder /go/src/github.com/paulojmdias/lokxy/lokxy /usr/local/bin/lokxy

CMD ["/usr/local/bin/lokxy"]
