{{- if .Values.horizontalPodAutoscaler.enabled }}
{{- $apiVersion := include "lokxy.horizontalPodAutoscaler.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "lokxy.fullname" . }}
  namespace: {{ include "lokxy.namespace" . }}
  labels:
    {{- include "lokxy.common.matchLabels" . | nindent 4 }}
    {{- include "lokxy.common.metaLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.horizontalPodAutoscaler.annotations | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "lokxy.fullname" . }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  {{- with .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.horizontalPodAutoscaler.customMetrics }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.horizontalPodAutoscaler.behavior.enabled }}
  behavior:
    {{- with .Values.horizontalPodAutoscaler.behavior.scaleDown }}
    scaleDown: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.horizontalPodAutoscaler.behavior.scaleUp }}
    scaleUp: {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
