{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "lokxy.fullname" . }}
  namespace: {{ include "lokxy.namespace" . }}
  labels:
    {{- include "lokxy.common.matchLabels" . | nindent 4 }}
    {{- include "lokxy.common.metaLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.verticalPodAutoscaler.annotations | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lokxy.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updatePolicy.updateMode | quote }}
  {{- with .Values.verticalPodAutoscaler.resourcePolicy }}
  resourcePolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
