horizontalPodAutoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

verticalPodAutoscaler:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
