apiVersion: v1
{{- if eq .Values.configStorageType "Secret" }}
kind: Secret
{{- else }}
kind: ConfigMap
{{- end }}
metadata:
  name: {{ template "lokxy.fullname" . }}
  namespace: {{ include "lokxy.namespace" . }}
  labels:
    {{- include "lokxy.common.matchLabels" . | nindent 4 }}
    {{- include "lokxy.common.metaLabels" . | nindent 4 }}
{{- if eq .Values.configStorageType "Secret" }}
data:
  config.yaml: {{- tpl .Values.config . | b64enc | nindent 4 }}
{{- else }}
data:
  config.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
{{- end -}}
