{{- if .Values.ingress.enabled }}
apiVersion: {{ include "lokxy.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "lokxy.fullname" . }}
  namespace: {{ include "lokxy.namespace" . }}
  labels:
    {{- include "lokxy.common.matchLabels" . | nindent 4 }}
    {{- include "lokxy.common.metaLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "lokxy.fullname" $ }}
                port:
                  number: {{ $.Values.ports.service }}
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
