networks:
  play:

services:
  loki1:
    image: grafana/loki:latest
    container_name: loki1
    ports:
      - "3101:3101"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -server.http-listen-port=3101
    expose:
      - 3101
    networks:
      - play

  loki2:
    image: grafana/loki:latest
    container_name: loki2
    ports:
      - "3102:3102"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -server.http-listen-port=3102
    expose:
      - 3102
    networks:
      - play

  lokxy:
    build:
      context: ../..
      dockerfile: Dockerfile.local
    image: lokxy/lokxy:latest
    container_name: lokxy
    volumes:
      - "./lokxy:/config"
    ports:
      - "3100:3100"
    expose:
      - 3100
    command: lokxy --config /config/lokxy.yaml --bind-addr=:3100 --metrics-addr=:9091
    networks:
      - play
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - loki1
      - loki2
