name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Weaver
        uses: open-telemetry/weaver/.github/actions/setup-weaver@74008737d0cd04cc91f4792da9e6702375fb512f # v0.22.1
      - name: Validate telemetry schema
        run: weaver --future registry check -r ./weaver/ --diagnostic-format gh_workflow_command
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: false
      - name: install dependencies
        run: make lint-install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
